language: node_js

node_js:
  - "8"

cache:
  yarn: true

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run bundle
  - npm run build
  - npm test
  - npm run report-coverage